export const items = [
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Acrylic", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Acrylic", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Acrylic", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Acrylic", imgName: "Yarn2.webp"},
    {name: "Bomull Kit", price: 79, material: "Bomull", imgName: "Yarn.webp"},
    {name: "Bomull Tunn Kit", price: 99, material: "Ull", imgName: "Yarn2.webp"},

]

